module mycpu_wrapper(
    input  ext_int_0,
    input  ext_int_1,
    input  clk,
    input  resetn,
    output [3:0]    MAXI_arid,
    output [31:0]   MAXI_araddr,
    output [3:0]    MAXI_arlen,
    output [2:0]    MAXI_arsize,
    output [1:0]    MAXI_arburst,
    output [1:0]    MAXI_arlock,
    output [3:0]    MAXI_arcache,
    output [2:0]    MAXI_arprot,
    output          MAXI_arvalid,
    input           MAXI_arready,
    input  [3:0]    MAXI_rid,
    input  [31:0]   MAXI_rdata,
    input  [1:0]    MAXI_rresp,
    input           MAXI_rlast,
    input           MAXI_rvalid,
    output          MAXI_rready,
    output [3:0]    MAXI_awid,
    output [31:0]   MAXI_awaddr,
    output [3:0]    MAXI_awlen,
    output [2:0]    MAXI_awsize,
    output [1:0]    MAXI_awburst,
    output [1:0]    MAXI_awlock,
    output [3:0]    MAXI_awcache,
    output [2:0]    MAXI_awprot,
    output          MAXI_awvalid,
    input           MAXI_awready,
    output [3:0]    MAXI_wid,
    output [31:0]   MAXI_wdata,
    output [3:0]    MAXI_wstrb,
    output          MAXI_wlast,
    output          MAXI_wvalid,
    input           MAXI_wready,
    input [3:0]     MAXI_bid,
    input [1:0]     MAXI_bresp,
    input           MAXI_bvalid,
    output          MAXI_bready,
    output [31:0]   debug_wb_pc,
    output [3:0]    debug_wb_rf_wen,
    output [4:0]    debug_wb_rf_wnum,
    output [31:0]   debug_wb_rf_wdata,
    output          debug_commit
);

mycpu_top nscscc_cpu(
    .aclk       (clk),
    .aresetn    (resetn),
    .ext_int    ({4'd0,ext_int_1,ext_int_0}),
    .arid       (MAXI_arid),
    .araddr     (MAXI_araddr),
    .arlen      (MAXI_arlen),
    .arsize     (MAXI_arsize),
    .arburst    (MAXI_arburst),
    .arlock     (MAXI_arlock),
    .arcache    (MAXI_arcache),
    .arprot     (MAXI_arprot),
    .arvalid    (MAXI_arvalid),
    .arready    (MAXI_arready),
    .rid        (MAXI_rid),
    .rdata      (MAXI_rdata),
    .rresp      (MAXI_rresp),
    .rlast      (MAXI_rlast),
    .rvalid     (MAXI_rvalid),
    .rready     (MAXI_rready),           
    .awid       (MAXI_awid),
    .awaddr     (MAXI_awaddr),
    .awlen      (MAXI_awlen),
    .awsize     (MAXI_awsize),
    .awburst    (MAXI_awburst),
    .awlock     (MAXI_awlock),
    .awcache    (MAXI_awcache),
    .awprot     (MAXI_awprot),
    .awvalid    (MAXI_awvalid),
    .awready    (MAXI_awready),
    .wid        (MAXI_wid),
    .wdata      (MAXI_wdata),
    .wstrb      (MAXI_wstrb),
    .wlast      (MAXI_wlast),
    .wvalid     (MAXI_wvalid),
    .wready     (MAXI_wready),
    .bid        (MAXI_bid),
    .bresp      (MAXI_bresp),
    .bvalid     (MAXI_bvalid),
    .bready     (MAXI_bready),
    .debug_wb_pc(debug_wb_pc),
    .debug_wb_rf_wen(debug_wb_rf_wen),
    .debug_wb_rf_wnum(debug_wb_rf_wnum),
    .debug_wb_rf_wdata(debug_wb_rf_wdata),
    .debug_commit(debug_commit)
);

endmodule
